# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - event-booking-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: eventapicontainer-apapfzb4dzhmemat.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6E5C2FE0DDA844BEBBA35008646250F2 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_FB387EDEF3CF49998FD07FAEE0EBAAAC }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: eventapicontainer-apapfzb4dzhmemat.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6E5C2FE0DDA844BEBBA35008646250F2 }}/eventapicontainer-apapfzb4dzhmemat.azurecr.io/event-booking-service:latest:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D9B28EC22B2F4B58BBD5D2F2F5E06787 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C280AE014C24E8B977297E963F7DFC2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61FD8F995355404CA92F89A724237C2D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'event-booking-service'
          slot-name: 'Production'
          images: 'eventapicontainer-apapfzb4dzhmemat.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6E5C2FE0DDA844BEBBA35008646250F2 }}/eventapicontainer-apapfzb4dzhmemat.azurecr.io/event-booking-service:latest:${{ github.sha }}'
          